services:
  - type: web
    name: sigizi-simple
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: SIGIZI_ENDPOINT
        sync: false
      - key: SIGIZI_USER
        sync: false
      - key: SIGIZI_PASS
        sync: false
      - key: APP_USER
        value: sigizi
      - key: APP_PASSWORD
        sync: false
